### PR TITLE
First version of Winterwind

### PR DESCRIPTION
**Pull request by joshdnichols**
No editing whatsoever.

### CODE REVIEW

**Comment by uliska** [comment]
Before merging your pull request I have one question:
There is this 5/4 bar. Is this due to some technical reason? Judging from the fact that you didn't comment on this I can imagine that you got confused with the measure and didn't notice that you'd have to put one big triplet over the first half of the measure.
Perhaps you might want to fix that before merging. (You can simply add a new commit and push it, it will then automatically be part of the pull request).

And of course I'd be interested in Finale's response to the idea of changing that music to a triplet ;-)

**Comment by joshdnichols** [comment]
I will "see" what that looks like.

**Comment by joshdnichols** [comment]
Oh, I have an update:

Finale absolutely HATES going back and changing stuff. I'm going to have to
re work that measure. My thought was, insomuch as this is a beauty contest,
I would beautify it and hide the idiosyncrasies in the final product (after
tweaking and such).

What say you?

I am going to just have to scratch that measure and start over in the
meantime, rather than try to adjust everything afterward.

IC,

Josh

**Comment by uliska** [comment]
> Finale absolutely HATES going back and changing stuff. I'm going to have to
> re work that measure. 

Of course this is interesting stuff.
How do Finale users change stuff in general? Of course it is a _very_ common task to review one's work, be it to fix errors like in this case or to review things in general (a composer who changes his mind ...).

> My thought was, insomuch as this is a beauty contest,
> I would beautify it and hide the idiosyncrasies in the final product (after
> tweaking and such).
> 
> What say you?

Nothing, because I don't really understand what you mean, sorry.

> I am going to just have to scratch that measure and start over in the
> meantime, rather than try to adjust everything afterward.

You mean you have to rewrite this (half?) measure instead of simply enclosing it in `\tuplet 2/3 { }`? OMG

**Comment by joshdnichols** [comment]
I just made the changes to the original files, and updated my `.md` file, and re-submitted the `.pdf`... that was a lot of work! Do I need to re-commit?

**Comment by joshdnichols** [comment]
Actually, I'll just send a new pull request.

**Comment by joshdnichols** [comment]
Did I do this right? : 
`C:\Users\Josh\Documents\GitHub\winterwind [master +0 ~3 -0]> git add Finale-2014/V1/ChoV1.md
C:\Users\Josh\Documents\GitHub\winterwind [master +0 ~1 -0 | +0 ~2 -0]> git add Finale-2014/V1/ChoV1.musx
C:\Users\Josh\Documents\GitHub\winterwind [master +0 ~2 -0 | +0 ~1 -0]> git add Finale-2014/V1/ChoV1.pdf
C:\Users\Josh\Documents\GitHub\winterwind [master +0 ~3 -0]> git push
Everything up-to-date
C:\Users\Josh\Documents\GitHub\winterwind [master +0 ~3 -0]> git pull
Already up-to-date.
C:\Users\Josh\Documents\GitHub\winterwind [master +0 ~3 -0]>`

**Pull request merged**
